### ISSUE TITLE
deprecation warning in `importlib.resources`

### ISSUE THREAD

**Issue by theendlessriver13** [matthiasdemuzere/w2w#17]
`importlib.resources.open_text`has already been deprecated and only `importlib.resources.files` is now supported, the backports work fine in < 3.8, but it is failing on `3.8` (first version without the backport) `AttributeError: module 'importlib.resources' has no attribute 'files'` 3.9 is fine again.
