### PR TITLE
fix deprecation warning for importlib resources

### LINKED ISSUE #17: deprecation warning in `importlib.resources`
`importlib.resources.open_text`has already been deprecated and only `importlib.resources.files` is now supported, the backports work fine in < 3.8, but it is failing on `3.8` (first version without the backport) `AttributeError: module 'importlib.resources' has no attribute 'files'` 3.9 is fine again.

### PR DESCRIPTION
**Pull request by theendlessriver13**
resolves #17

this should silence the deprecation warnings. In combination with #24 this should fix all warnings caused by this package. All existing warnings are caused by dependencies.

### CODE REVIEW

**Comment by matthiasdemuzere** [comment]
Looks good to me!
